language: java
 
sudo: false
 
jdk: 
  - openjdk14

script:
  - mvn clean package -Ptest

after_success:
- export CODECOV_TOKEN="5a739b4c-2b8b-40ff-a871-54729303bacb"
- bash <(curl -s https://codecov.io/bash)
  
notifications:
  email:
    recipients:
      - kirilldan94@mail.ru
    on_success: never # default: change
    on_failure: always # default: always

